# Generated by Django 3.0.3 on 2020-02-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinochios', '0004_menuitem_menu_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuoptionaddon',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='menuoptionaddon',
            name='menu_item',
            field=models.ManyToManyField(to='pinochios.MenuItem'),
        ),
    ]
