# Generated by Django 3.0.3 on 2020-02-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinochios', '0005_auto_20200217_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuoptionaddon',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='add_ons',
            field=models.ManyToManyField(to='pinochios.MenuOptionAddOn'),
        ),
    ]
