# Generated by Django 3.0.3 on 2020-02-17 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinochios', '0006_auto_20200217_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemoption',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_options',
            field=models.ManyToManyField(to='pinochios.MenuItemOption'),
        ),
        migrations.CreateModel(
            name='OptionPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('itemOption', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pinochios.MenuItemOption')),
                ('meal_size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pinochios.MealSize')),
            ],
        ),
        migrations.CreateModel(
            name='AddOnPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pinochios.MenuOptionAddOn')),
                ('meal_size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pinochios.MealSize')),
            ],
        ),
    ]
