# Generated by Django 3.0.3 on 2020-02-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinochios', '0008_auto_20200217_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemoption',
            name='meal_size',
        ),
    ]
