# Generated by Django 3.0.3 on 2020-07-13 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinochios', '0010_auto_20200217_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAddOnCountOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countValue', models.IntegerField()),
                ('small_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('large_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on_name', models.CharField(max_length=255)),
                ('small_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('large_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuaddonprice',
            name='add_on',
        ),
        migrations.RemoveField(
            model_name='menuaddonprice',
            name='meal_size',
        ),
        migrations.RemoveField(
            model_name='menuoptionprice',
            name='itemOption',
        ),
        migrations.RemoveField(
            model_name='menuoptionprice',
            name='meal_size',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='add_ons',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='add_ons',
        ),
        migrations.AddField(
            model_name='menuitemoption',
            name='large_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='menuitemoption',
            name='small_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='order_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinochios.OrderItem'),
        ),
        migrations.DeleteModel(
            name='MealSize',
        ),
        migrations.DeleteModel(
            name='MenuAddOnPrice',
        ),
        migrations.DeleteModel(
            name='MenuOptionAddOn',
        ),
        migrations.DeleteModel(
            name='MenuOptionPrice',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='add_on_count_options',
            field=models.ManyToManyField(to='pinochios.ItemAddOnCountOption'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='add_on_options',
            field=models.ManyToManyField(to='pinochios.MenuItemAddOn'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='add_on_count_options',
            field=models.ManyToManyField(to='pinochios.ItemAddOnCountOption'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='add_on_options',
            field=models.ManyToManyField(to='pinochios.MenuItemAddOn'),
        ),
    ]
