# Generated by Django 3.0.3 on 2021-01-27 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinochios', '0011_auto_20200713_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='add_on_count_options',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='add_on_count_options',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item_option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='pinochios.MenuItemOption'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pinochios.OrderItem'),
        ),
        migrations.DeleteModel(
            name='ItemAddOnCountOption',
        ),
    ]
