# Generated by Django 3.0.3 on 2021-01-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinochios', '0013_auto_20210127_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='add_on_options',
            field=models.ManyToManyField(blank=True, to='pinochios.MenuItemAddOn'),
        ),
    ]
